# Configuração da Conexão com o Banco de Dados (MySQL)
db.url=jdbc:mysql://localhost:3306/gestao_comercial?useSSL=false&serverTimezone=UTC
db.username=root
db.password=936558Ma#
db.driver=com.mysql.cj.jdbc.Driver